clinica/clinica/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("profesional/", include("profesional.urls")),
    path("paciente/", include("paciente.urls")),
    path("sede/", include("sede.urls")),
    
]

clinica/home/urls.py
from django.urls import path

from home import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search, name="search"),
]

clinica/profesional/urls.py
from django.urls import path

from profesional import views

app_name = "profesional"
urlpatterns = [
    path("profesionals", views.profesionals, name="profesional-list"),
    path("profesional/add", views.create_profesional, name="profesional-add"),
]

clinica/profesional/models.py
from django.db import models

class Profesional(models.Model):
    name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    email = models.EmailField()
    especialidad = models.CharField(max_length=40)
    tel= models.IntegerField()
    
    def __str__(self):
        return f"Profesional: {self.name} {self.last_name} | Especialidad: {self.especialidad}"

clinica/profesional/forms.py
from django import forms


class ProfesionalForm(forms.Form):
    name = forms.CharField(
        label="Nombre del Profesional",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "profesional-name",
                "placeholder": "Nombre de profesional",
                "required": "True",
            }
        ),
    )
    last_name = forms.CharField(
        label="Apellido del profesional",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "profesional-last-name",
                "placeholder": "Apellido del profesional",
                "required": "True",
            }
        ),
    )
    email = forms.EmailField(
        label="Email:",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "profesional-email",
                "placeholder": "email",
                "required": "True",
            }
        ),
    )
    especialidad = forms.CharField(
        label="Especialidad:",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "profesional-especialidad",
                "placeholder": "Especialidad",
                "required": "True",
            }
        ),
    )
    tel = forms.IntegerField(
        label="Telefono:",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "profesional-tel",
                "placeholder": "Telefono",
                "required": "True",
            }
        ),
    )

clinica/profesional/views.py
from django.shortcuts import render
from django.contrib import messages

from profesional.models import Profesional
from profesional.forms import ProfesionalForm


def get_profesionals(request):
    profesionals = Profesional.objects.all()
    return profesionals


def create_profesional(request):
    if request.method == "POST":
        profesional_form = ProfesionalForm(request.POST)
        if profesional_form.is_valid():
            data = profesional_form.cleaned_data
            actual_objects = Profesional.objects.filter(
                name=data["name"],
                last_name=data["last_name"],
                email=data["email"],
            ).count()
            print("actual_objects", actual_objects)
            if actual_objects:
                messages.error(
                    request,
                    f"El profesional {data['name']} {data['last_name']} ya está creado",
                )
            else:
                profesional = Profesional(
                    name=data["name"],
                    last_name=data["last_name"],
                    email=data["email"],
                    especialidad=data["especialidad"],
                    tel=data["tel"],
                )
                profesional.save()
                messages.success(
                    request,
                    f"Profesional {data['name']} {data['last_name']} creado exitosamente!",
                )

            return render(
                request=request,
                context={"profesionals": get_profesionals(request)},
                template_name="profesional/profesional_list.html",
            )

    profesional_form = ProfesionalForm(request.POST)
    context_dict = {"form": profesional_form}
    return render(
        request=request,
        context=context_dict,
        template_name="profesional/profesional_form.html",
    )


def profesionals(request):
    profesionals = Profesional.objects.all()

    context_dict = {"profesionals": profesionals}

    return render(
        request=request,
        context=context_dict,
        template_name="profesional/profesional_list.html",
    )

clinica/profesional/templates/profesional/profesional_form.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Profesional
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('../../static/home/assets/img/medicos.png')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h2>Formulario para guardar profesional</h2>
                    <span class="subheading"> CLINICA </span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block my_blog_content %}
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Guardar profesional" />
        </form>
    </div>
    <!-- Divider-->
    <hr class="my-4" />
{% endblock %}

clinica/profesional/templates/profesional/profesional_list.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Profesional
{% endblock %}

{% block my_blog_header %}
    <header class="masthead" style="background-image: url('../../static/home/assets/img/medicos.png')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-15 col-lg-16 col-xl-14">
                    <div class="site-heading">
                        <h1>Profesionales</h1>
                        <span class="subheading"> CLINICA </span>
                    </div>
                </div>
            </div>
            <a class="button_custom" href="{% url 'profesional:profesional-add' %}">Crear nuevo Profesional</a>
        </div>
    </header>
{% endblock %}

{% block my_blog_content %}
    {% for profesional in profesionals %}
        <!-- Post preview-->
        <div class="post-preview">
            <h2 class="post-title">Este es el Profesional: {{ profesional.name }}  {{ profesional.last_name }}</h2>
            <h3 class="post-subtitle">Email: {{ profesional.email }}</h3>
            <h3 class="post-subtitle">Especialidad: {{ profesional.especialidad }}</h3>
            <h3 class="post-subtitle">Telefono: {{ profesional.tel }}</h3>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
    {% endfor %}
{% endblock %}