clinica/clinica/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("profesional/", include("profesional.urls")),
    path("paciente/", include("paciente.urls")),
    path("sede/", include("sede.urls")),
    
]

clinica/home/urls.py
from django.urls import path

from home import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search, name="search"),
]

clinica/paciente/urls.py
from django.urls import path

from paciente import views

app_name = "paciente"
urlpatterns = [
    path("pacientes", views.pacientes, name="paciente-list"),
    path("paciente/add", views.create_paciente, name="paciente-add"),
]

clinica/profesional/urls.py
from django.urls import path

from profesional import views

app_name = "profesional"
urlpatterns = [
    path("profesionals", views.profesionals, name="profesional-list"),
    path("profesional/add", views.create_profesional, name="profesional-add"),
]

clinica/sede/urls.py
from django.urls import path

from sede import views

app_name = "sede"
urlpatterns = [
    path("sedes", views.sedes, name="sede-list"),
    path("sede/add", views.create_sede, name="sede-add"),
]

clinica/home/models.py
from django.db import models

# Create your models here.

clinica/home/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from django.db.models import Q
from profesional.models import Profesional


def index(request):
    return render(
        request=request,
        context={},
        template_name="home/index.html",
    )


def search(request):
    search_param = request.GET["search_param"]
    print("search: ", search_param)
    context_dict = dict()
    if search_param:
        query = Q(name__contains=search_param)
        query.add(Q(last_name__contains=search_param), Q.OR)
        profesionales = Profesional.objects.filter(query)
        context_dict.update(
            {
                "profesionales": profesionales,
                "search_param": search_param,
            }
        )
    return render(
        request=request,
        context=context_dict,
        template_name="home/index.html",
    )

clinica/home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
    <head>

        {% load static %}

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block my_blog_title %}
                Home
            {% endblock %}
        </title>
        <link rel="icon" type="image/x-icon" href="{% static 'home/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'home/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'home:index' %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'profesional:profesional-list' %}">Profesionales</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'paciente:paciente-list' %}">Pacientes</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'sede:sede-list' %}">Sedes</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block my_blog_header %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('../../static/home/assets/img/home1.png')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>CLINICA</h1>
                            <span class="subheading">INFORMACION ONLINE</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock %}
        <!-- Messages-->
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert {{ message.tags }}" role="alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                        <!-- Divider-->
                        <hr class="my-4" />
                    {% endif %}
                </div>
            </div>
        </div>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->
                    {% block my_blog_content %}

                    <!-- Buscador -->
                    <h2>Buscador de Profesionales</h2>
                    <form action="{% url 'home:search' %}" method="GET">
                        <div>
                            <input type="text" name="search_param" id="profesional_code_or_name" placeholder="Buscar.."
                            {% if search_param %} value="{{ search_param }}" {% endif %}
                            >
                            <input type="submit" value="Buscar">
                            <a style="color: rgb(9, 9, 124)" href="{% url 'home:index' %}"><i class="fa fa-undo"></i></a>
                        </div>
                    </form>
                    <!-- Divider-->
                    <hr class="my-4" />

                    <!-- Si hay resultados en el buscador los presenta -->
                    {% if profesionales %}
                    {% for profesional in profesionales %}
                        <!-- Post preview-->
                        <div class="post-preview">
                            <h2 class="post-title">Este es el profesional: {{ profesional.name }} {{ profesional.last_name }}</h2>
                            <h3 class="post-subtitle">Que tiene la especialidad: {{ profesional.especialidad }}</h3>
                            <h3 class="post-subtitle">Telefono: {{ profesional.tel }}</h3>
                        </div>
                        <!-- Divider-->
                        <hr class="my-4" />
                    {% endfor %}
                    {% endif %}
                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Entrega Intermedia del Proyecto Final - CLINICA</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'home/js/scripts.js' %}"></script>
    </body>
</html>