clinica/clinica/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("profesional/", include("profesional.urls")),
    path("paciente/", include("paciente.urls")),
    path("sede/", include("sede.urls")),
    
]

clinica/home/urls.py
from django.urls import path

from home import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search, name="search"),
]

clinica/paciente/urls.py
from django.urls import path

from paciente import views

app_name = "paciente"
urlpatterns = [
    path("pacientes", views.pacientes, name="paciente-list"),
    path("paciente/add", views.create_paciente, name="paciente-add"),
]

clinica/paciente/models.py
from django.db import models

class Paciente(models.Model):
    name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    dni = models.IntegerField()
    email = models.EmailField()
    tel= models.IntegerField()
    
    def __str__(self):
        return f"Paciente: {self.name} {self.last_name} | dni: {self.dni}"

clinica/paciente/forms.py
from django import forms


class PacienteForm(forms.Form):
    name = forms.CharField(
        label="Nombre del Paciente",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "paciente-name",
                "placeholder": "Nombre de paciente",
                "required": "True",
            }
        ),
    )
    last_name = forms.CharField(
        label="Apellido del paciente",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "paciente-last-name",
                "placeholder": "Apellido del paciente",
                "required": "True",
            }
        ),
    )
    email = forms.EmailField(
        label="Email:",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "paciente-email",
                "placeholder": "email",
                "required": "True",
            }
        ),
    )
    dni = forms.IntegerField(
        label="Dni:",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "paciente-dni",
                "placeholder": "Dni",
                "required": "True",
            }
        ),
    )
    tel = forms.IntegerField(
        label="Telefono:",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "paciente-tel",
                "placeholder": "Telefono",
                "required": "True",
            }
        ),
    )

clinica/paciente/views.py
from django.shortcuts import render
from django.contrib import messages

from paciente.models import Paciente
from paciente.forms import PacienteForm


def get_pacientes(request):
    pacientes = Paciente.objects.all()
    return pacientes


def create_paciente(request):
    if request.method == "POST":
        paciente_form = PacienteForm(request.POST)
        if paciente_form.is_valid():
            data = paciente_form.cleaned_data
            actual_objects = Paciente.objects.filter(
                name=data["name"],
                last_name=data["last_name"],
                dni=data["dni"],
            ).count()
            print("actual_objects", actual_objects)
            if actual_objects:
                messages.error(
                    request,
                    f"El paciente {data['name']} {data['last_name']} ya está creado",
                )
            else:
                paciente = Paciente(
                    name=data["name"],
                    last_name=data["last_name"],
                    email=data["email"],
                    dni=data["dni"],
                    tel=data["tel"],
                )
                paciente.save()
                messages.success(
                    request,
                    f"Paciente {data['name']} {data['last_name']} creado exitosamente!",
                )

            return render(
                request=request,
                context={"pacientes": get_pacientes(request)},
                template_name="paciente/paciente_list.html",
            )

    paciente_form = PacienteForm(request.POST)
    context_dict = {"form": paciente_form}
    return render(
        request=request,
        context=context_dict,
        template_name="paciente/paciente_form.html",
    )


def pacientes(request):
    pacientes = Paciente.objects.all()

    context_dict = {"pacientes": pacientes}

    return render(
        request=request,
        context=context_dict,
        template_name="paciente/paciente_list.html",
    )

clinica/paciente/templates/paciente/paciente_form.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Paciente
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('../../static/home/assets/img/paciente.png')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h2>Formulario para guardar paciente</h2>
                    <span class="subheading"> CLINICA </span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block my_blog_content %}
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Guardar paciente" />
        </form>
    </div>
    <!-- Divider-->
    <hr class="my-4" />
{% endblock %}

clinica/paciente/templates/paciente/paciente_list.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Paciente
{% endblock %}

{% block my_blog_header %}
    <header class="masthead" style="background-image: url('../../static/home/assets/img/paciente.png')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-15 col-lg-16 col-xl-14">
                    <div class="site-heading">
                        <h1>Pacientes</h1>
                        <span class="subheading"> CLINICA </span>
                    </div>
                </div>
            </div>
            <a class="button_custom" href="{% url 'paciente:paciente-add' %}">Crear nuevo Paciente</a>
        </div>
    </header>
{% endblock %}

{% block my_blog_content %}
    {% for paciente in pacientes %}
        <!-- Post preview-->
        <div class="post-preview">
            <h2 class="post-title">Este es el Paciente: {{ paciente.name }}  {{ paciente.last_name }}</h2>
            <h3 class="post-subtitle">Email: {{ paciente.email }}</h3>
            <h3 class="post-subtitle">Dni: {{ paciente.dni }}</h3>
            <h3 class="post-subtitle">Telefono: {{ paciente.tel }}</h3>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
    {% endfor %}
{% endblock %}